--
--INSERT INTO public.categoria(nome, descricao) VALUES ('bebidas', 'alcoólicos');
--INSERT INTO public.categoria(nome, descricao) VALUES ('congelados', 'alimentos');
--INSERT INTO public.categoria(nome, descricao) VALUES ('carnes', 'alimentos');
--
--INSERT INTO public.produto(nome, valor_produto, status_produto, id_categoria) VALUES ('Arroz', 10.50, true, 1);
--INSERT INTO public.produto(nome, valor_produto, status_produto, id_categoria) VALUES ('Bolacha', 10.50, true, 2);
--INSERT INTO public.produto(nome, valor_produto, status_produto, id_categoria) VALUES ('Feijão', 10.50, true, 3);
